server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: noteservice
          uri: http://localhost:8081/
          predicates:
            - Path=/notes/**
        - id: taskservice
          uri: http://localhost:8082/
          predicates:
            - Path=/tasks/**
